---
# apply some pretty generic configurations

- name: config| create config directories for {{ user.username }}
  become: true
  file:
    path: "~{{ user.username }}/.var/app/com.belledonnecommunications.linphone/config/linphone/"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: 'u=rwx,go=r'
  when: user.username is defined

- name: config| template out a config for {{ user.username }}
  template:
    src: linphonerc.j2
    dest: "~{{ user.username }}/.var/app/com.belledonnecommunications.linphone/config/linphone/linphonerc"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    backup: true
  when: user.username is defined

# - name: config| write a config file if irc_nick is specified
#   template:
#     src: hexchat.conf.j2
#     dest: "~{{ item.username }}/.var/app/io.github.Hexchat/config/hexchat/hexchat.conf"
#     owner: "{{ item.username }}"
#     group: "{{ item.username }}"
#     backup: true
#   with_items: "{{ users }}"
#   when: item.username is defined
